# DataSource Config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/transformerdb?characterEncoding=UTF-8
#    username: root
#    password: root
    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
    url: jdbc:h2:~/transformerdb # jdbc:h2:mem:test_mem
    username: root
    password: test
    druid:
      filters: stat
      initial-size: 2
      max-active: 300
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 200
  h2:
    console:
      enabled: true
      path: /h2db
      settings:
        trace: false
        web-allow-others: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

sftp:
  client:
    host: 127.0.0.1
    port: 22
    username: root
    password: orange
    identity: ~/.ssh/id_rsa
    passphrase:
